# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
